services:
  api:
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:prepare && bin/rails server -b 0.0.0.0"
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=sqlite3:/app/db/development.sqlite3

  frontend:
    build: ./frontend
    command: bash -c "npm install && npm run dev -- --host"
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - api
