# frozen_string_literal: true

source 'https://rubygems.org'

gem 'puma', '>= 5.0'
gem 'rails', '~> 8.0.2'
gem 'sqlite3', '>= 2.1'
gem 'tzinfo-data', platforms: %i[windows jruby]

gem 'solid_cable'
gem 'solid_cache'
gem 'solid_queue'

gem 'bootsnap', require: false
gem 'kamal', require: false
gem 'thruster', require: false

gem 'rack-cors'

group :development, :test do
  gem 'brakeman', require: false
  gem 'rspec-rails', '~> 6.0'
  gem 'rubocop', '~> 1.63', require: false
  gem 'rubocop-rails', '~> 2.32', require: false
end
